name: Test & Deploy Workflow
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Deployment Window
        id: tiem-check
        run: |-
          curl -X POST https://agonic-meandrous-misha.ngrok-free.dev/api/check \
            -H "Authorization: Bearer ${{ secrets.TIEM_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repositoryId":"cmidaukst0003y6itlpzr2brj","branch":"${{ github.ref_name }}","environmentId":"cmidavcub0005y6itp06lq9fc"}' \
            -o response.json

          allowed=$(jq -r '.allowed' response.json)
          if [ "$allowed" != "true" ]; then
            reason=$(jq -r '.reason' response.json)
            echo "::error::Deployment blocked: $reason"
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build step
        run: echo "Building the project..."
      - name: Run tests
        run: echo "Running tests... (dummy)"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check Deployment Window
        id: tiem-check
        run: |-
          curl -X POST https://agonic-meandrous-misha.ngrok-free.dev/api/check \
            -H "Authorization: Bearer ${{ secrets.TIEM_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repositoryId":"cmidaukst0003y6itlpzr2brj","branch":"${{ github.ref_name }}","environmentId":"cmidavcub0005y6itp06lq9fc"}' \
            -o response.json

          allowed=$(jq -r '.allowed' response.json)
          if [ "$allowed" != "true" ]; then
            reason=$(jq -r '.reason' response.json)
            echo "::error::Deployment blocked: $reason"
            exit 1
          fi
      - name: Deploy step
        run: |
          echo "Starting deployment..."
          echo "This is a dummy deploy job."
          echo "Deployment complete ✔️"
